[main]
name = "wre"
entry_points=["e","b","c"]
[e]
type="button"
callback="egr"
name="e"
opt_params={callback="egr"}
[b]
type="button"

name="mutton"
opt_params={callback="egr"}
[c]
type="button"

name="wutton"
opt_params={callbdack="egr"}